/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uh1_atm;

import javax.swing.JOptionPane;

/**
 *
 * @author Arischa Nur Fadilah
 */
public class ATM extends javax.swing.JFrame {
    int saldo=100000;
    String inputsetor, inputtarik;
    int str, z, t;
    /**
     * Creates new form ATM
     */
    public ATM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        tarik = new javax.swing.JButton();
        ceksaldo = new javax.swing.JButton();
        setor = new javax.swing.JButton();
        bantuan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Pilih Transaksi");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 90, 14);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(130, 200, 120, 40);

        tarik.setText("Penarikan");
        tarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarikActionPerformed(evt);
            }
        });
        getContentPane().add(tarik);
        tarik.setBounds(50, 140, 120, 40);

        ceksaldo.setText("Cek Saldo");
        ceksaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceksaldoActionPerformed(evt);
            }
        });
        getContentPane().add(ceksaldo);
        ceksaldo.setBounds(50, 70, 120, 40);

        setor.setText("Penyetoran");
        setor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setorActionPerformed(evt);
            }
        });
        getContentPane().add(setor);
        setor.setBounds(210, 70, 120, 40);

        bantuan.setText("Bantuan");
        bantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bantuanActionPerformed(evt);
            }
        });
        getContentPane().add(bantuan);
        bantuan.setBounds(210, 140, 120, 40);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void ceksaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceksaldoActionPerformed
        
        JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : "+saldo);
        
    }//GEN-LAST:event_ceksaldoActionPerformed

    private void setorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setorActionPerformed
        inputsetor = JOptionPane.showInputDialog(null,"Masukkan Jumlah Penyetoran : ");
        str = Integer.parseInt(inputsetor);
        setorclass hasil = new setorclass();
        hasil.menabung(saldo, str);
        saldo = hasil.getSaldo();
        
    }//GEN-LAST:event_setorActionPerformed

    private void tarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarikActionPerformed
        inputtarik = JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan : ");
        t = Integer.parseInt(inputtarik);
        tarikclass mengambil = new tarikclass();
        mengambil.ambil(saldo,t);
        saldo = mengambil.getSaldo();
        
    }//GEN-LAST:event_tarikActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        JOptionPane.showMessageDialog(null, "Terima Kasih telah menggunakan ATM BRI");
        System.exit(0);
    }//GEN-LAST:event_keluarActionPerformed

    private void bantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bantuanActionPerformed
        JOptionPane.showMessageDialog(null,"Cara Penggunaan Aplikasi \n1. Masukkan PIN dengan benar\n2. Bertransaksilah dengan benar sesuai pilihan\n3. Gunakan uang sesuai kebutuhan dan rajinlah menabung","INFO",1);
    }//GEN-LAST:event_bantuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bantuan;
    private javax.swing.JButton ceksaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton setor;
    private javax.swing.JButton tarik;
    // End of variables declaration//GEN-END:variables
}
